# Dockerfile.dev – ENV DEVELOPPPEMENT Angular
FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Expose le port de ng serve
EXPOSE 4200

# Commande de démarrage : serveur de développement Angular
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
